### ISSUE TITLE
How do I return a custom Result for error handling in Rust just like how in Python you can throw your own custom Exceptions?

### ISSUE THREAD

**Issue by dragos-ionescu** [alexzanderr/rust-dev-guide#1]
**Rust differs from other programming languages on the topic of error handling. Where other languages put exceptions in one big pile, Rust makes a distinction between `recoverable` and `unrecoverable` errors.**

Recoverable errors are the kind of errors that we are familiar with:
*   Making an HTTP request when the URL is invalid or when there is no Internet.
*   Trying to read from a file that doesn't exist.

These kinds of errors can be recovered from because we can show the user a friendly error message and carry on with doing other stuff like rendering an interface.

Unrecoverable errors are a sign of bad programming like accessing a buffer beyond its capacity or they are the result of an action that was tried and cannot be repaired like accessing a protected file (there is nothing we can do if we don't have read and write access to file 'file.txt').

Yet again, Rust differs because it doesn't have an exception system like the one that we are familiar with: `try-catch` and `throw Exception`. Instead, we are given a `Result` enum that encapsulates the successful result of an operation in `Ok`, or the error upon a failure in `Err`.

``` python
try:
    file = open("file.txt", "r")
except FileNotFoundError:
    file = open("file.txt", "w")
```

The exception system in Python is simple and straightforward. In the above example, `open` in read mode throws a `FileNotFoundError` is the file doesn't exist.

``` rust
let file = match fs::read_to_string("file.txt") {
    Ok(value) => value,
    Err(error) => match File::create("file.txt") {
        Ok(_) => {}
        Err(_) => panic!(),
    },
};
```

I like this approach better because a `Result` you can always return from a function, unlike traditional exceptions where you were usually returning the success but if you ever encountered an exception you had to think really hard what to do with it later down the line - propagate it, resolve it or wrap in your own custom exception. Something more, from analyzing the code, you can see exactly what part it's going to return a Result (and possibly an error) which makes reasoning about logic much easier and natural.

So far so good. Now what is the problem that I have with this?

In Python you can throw your own Exceptions, say `if "file doesn't exist" throw MyOwnCustomException`, but how would you do that in Rust?

So far, I've only been shown methods that return Result but never created my own logic that returns Result.

Can you give me an example of a Rust program that checks for some logic and returns result?

**Comment by alexzanderr** [comment]
Hello and thank you for interest in the guide of development with Rust!

I will make a PR with a solution for your case. Stay still!

**Comment by alexzanderr** [comment]
this response is for:
> In Python you can throw your own Exceptions, say if "file doesn't exist" throw MyOwnCustomException, but how would you do that in Rust?

one quick, easy and simple way is to define your custom errors in an `enum` and then use `thiserror` crate to implement automatically the `Error` trait for your enum variants.

this way you define sort of a wrapper error type or a type that contains many errors types to handle your situation, which could be reading a number from stdin and then parse it.

in that specific case you encounter 2 different kind of errors:
- [`std::io::Error`](https://doc.rust-lang.org/std/io/struct.Error.html)
- [`std::num::ParseIntError`](https://doc.rust-lang.org/std/num/struct.ParseIntError.html)

here's the solution for this case:
https://github.com/alexzanderr/rust-dev-guide/blob/issue-1/topics/error-handling/issue-1/src/bin/solution-1.rs

this way is better because normally you would have to implement (manually) the Error trait for your custom error, which would be a struct, and the Display trait and many more traits, which is actually annoying.

this way is more recommended and i've seen many developers use this approach to handle errors in their crates/projects.

**Comment by alexzanderr** [comment]
i will write more answers to this discussion, one by one, this is not the end. more will come.

**Comment by alexzanderr** [comment]
this is the most basic/bare bones example
```rust
// use your custom error types with thiserror crate
fn read_number() -> std::io::Result<i32> {
    let mut buffer = String::new();
    std::io::stdin().read_line(&mut buffer)?;

    let number = buffer.trim().parse::<i32>()?;

    Ok(number)
}

fn main() {
    let result = read_number();
    dbg!(&result);
}
```
note that you have only 1 result type that you can return, but your code from the function can return 2 different types of errors, which is not good.


not good because of this:
```sh
error[E0277]: `?` couldn't convert the error to `std::io::Error`
 --> topics/error-handling/issue-1/src/bin/bare-bones-way.rs:6:46
  |
2 | fn read_number() -> std::io::Result<i32> {
  |                     -------------------- expected `std::io::Error` because of this
...
6 |     let number = buffer.trim().parse::<i32>()?;
  |                                              ^ the trait `From<ParseIntError>` is not implemented for `std::io::Error`
  |
  = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
  = help: the following other types implement trait `From<T>`:
            <std::io::Error as From<ErrorKind>>
            <std::io::Error as From<IntoInnerError<W>>>
            <std::io::Error as From<NulError>>
  = note: required for `Result<i32, std::io::Error>` to implement `FromResidual<Result<Infallible, ParseIntError>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `issue-1` due to previous error
```


note that the `?` operator is just syntactic sugar
this line `std::io::stdin().read_line(&mut buffer)?;`

expands to
```rust
    match std::io::stdin().read_line(&mut buffer) {
        Ok(value) => value,
        Err(error) => return Err(error.into()),
    }
```
note the `into()` call, has something to do with the [`Into`](https://doc.rust-lang.org/std/convert/trait.Into.html#) trait which is the reciprocal of the [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) trait

**Comment by alexzanderr** [comment]
normally you need to implement the `From` trait for conversion between errors, because errors are structs of different types.

note that deriving `thiserror::Error` expands to something similar to this:
```rust
#[derive(Debug)]
enum Error {
    ParseIntError(std::num::ParseIntError),
    ParseFloatError(std::num::ParseFloatError),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ParseIntError(e) => write!(f, "ParseIntError: {}", e.to_string()),
            Self::ParseFloatError(e) => write!(f, "ParseFloatError: {}", e.to_string()),
        }
    }
}

impl std::error::Error for Error {}

// Convert `std::num::ParseIntError` to `Error`
impl From<std::num::ParseIntError> for Error {
    fn from(err: std::num::ParseIntError) -> Self {
        Self::ParseIntError(err)
    }
}

// Convert `std::num::ParseFloatError` to `Error`
impl From<std::num::ParseFloatError> for Error {
    fn from(err: std::num::ParseFloatError) -> Self {
        Self::ParseFloatError(err)
    }
}
```
also note that here are implementations of `From` trait for every enum variant

the thiserror::Error implements the `From` trait automatically and helps you get around the problem of implement manually

**Comment by alexzanderr** [comment]
now. what if you want to implement to From trait manually for our `bare-bones` situation ?

ok lets try then. this would be a dummy implementation:
```rust
use std::io::ErrorKind;
use std::num::ParseIntError;

impl From<ParseIntError> for std::io::Error {
    fn from(error: ParseIntError) {
        // second argument is the message
        Self::new(ErrorKind::Other, error.to_string())
    }
}
```
error.to_string() is the message, here is the source code for the `to_string` implementation in std lib
```rust

#[stable(feature = "rust1", since = "1.0.0")]
impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.repr.data() {
            ErrorData::Os(code) => {
                let detail = sys::os::error_string(code);
                write!(fmt, "{detail} (os error {code})")
            }
            ErrorData::Custom(ref c) => c.error.fmt(fmt),
            ErrorData::Simple(kind) => write!(fmt, "{}", kind.as_str()),
            ErrorData::SimpleMessage(msg) => msg.message.fmt(fmt),
        }
    }
}
```
its actually returning a string message

first of all.
- this actually doesnt make any sense, because its messy to work with `ErrorKind` which is from `std::io`, what if you dont find any suitable enum variant from `std::io::ErrorKind` to express your error kind more specifically? thats not really good
- second of all. the code doesnt compile!
```sh
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
 --> topics/error-handling/issue-1/src/bin/bare-bones-way.rs:4:1
  |
4 | impl From<ParseIntError> for std::io::Error {
  | ^^^^^-------------------^^^^^--------------
  | |    |                       |
  | |    |                       `std::io::Error` is not defined in the current crate
  | |    `ParseIntError` is not defined in the current crate
  | impl doesn't use only types from inside the current crate
  |
  = note: define and implement a trait or new type instead

For more information about this error, try `rustc --explain E0117`.
error: could not compile `issue-1` due to previous error
```
 uh-oh... you cant implement traits which are not defined in the current crate for types that are not defined in the current crate. this is how rust works.

so this approach is not good at all.

now if you know all of these interesting facts you are left with:
- manually defining an a struct/or an enum which implements Error trait, and also implement Display, Debug, and many more functions or traits manually
- use the approach which derives `thiserror::Error`, which is much more easy

ofc there are debates, some want to implement manually, some do not.

for beginners its good to understand the core concepts and use the thiserror, some advanced users like to implement manually because they are more control over the resulting implementation of the code (for more custom stuff)

**Comment by alexzanderr** [comment]
for the thiserror approach, you can use `cargo expand` to see the actualy implementation, which is this one:

```rust
#![feature(prelude_import)]
//! this file is the answer for this question
//! In Python you can throw your own Exceptions, say `if "file doesn't exist" throw MyOwnCustomException`, but how would you do that in Rust?
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
enum ReadNumberError {
    #[error("read line error")]
    ReadLine(#[from] std::io::Error),
    #[error("parse int error")]
    ParseInt(#[from] std::num::ParseIntError),
}
#[allow(unused_qualifications)]
impl std::error::Error for ReadNumberError {
    fn source(&self) -> std::option::Option<&(dyn std::error::Error + 'static)> {
        use thiserror::__private::AsDynError;
        #[allow(deprecated)]
        match self {
            ReadNumberError::ReadLine { 0: source, .. } => {
                std::option::Option::Some(source.as_dyn_error())
            }
            ReadNumberError::ParseInt { 0: source, .. } => {
                std::option::Option::Some(source.as_dyn_error())
            }
        }
    }
}
#[allow(unused_qualifications)]
impl std::fmt::Display for ReadNumberError {
    fn fmt(&self, __formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        #[allow(unused_variables, deprecated, clippy::used_underscore_binding)]
        match self {
            ReadNumberError::ReadLine(_0) => {
                __formatter.write_fmt(::core::fmt::Arguments::new_v1(&["read line error"], &[]))
            }
            ReadNumberError::ParseInt(_0) => {
                __formatter.write_fmt(::core::fmt::Arguments::new_v1(&["parse int error"], &[]))
            }
        }
    }
}
#[allow(unused_qualifications)]
impl std::convert::From<std::io::Error> for ReadNumberError {
    #[allow(deprecated)]
    fn from(source: std::io::Error) -> Self {
        ReadNumberError::ReadLine { 0: source }
    }
}
#[allow(unused_qualifications)]
impl std::convert::From<std::num::ParseIntError> for ReadNumberError {
    #[allow(deprecated)]
    fn from(source: std::num::ParseIntError) -> Self {
        ReadNumberError::ParseInt { 0: source }
    }
}
#[automatically_derived]
impl ::core::fmt::Debug for ReadNumberError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            ReadNumberError::ReadLine(__self_0) => {
                ::core::fmt::Formatter::debug_tuple_field1_finish(f, "ReadLine", &__self_0)
            }
            ReadNumberError::ParseInt(__self_0) => {
                ::core::fmt::Formatter::debug_tuple_field1_finish(f, "ParseInt", &__self_0)
            }
        }
    }
}
fn read_number() -> std::result::Result<i32, ReadNumberError> {
    let mut buffer = String::new();
    std::io::stdin().read_line(&mut buffer)?;
    let number = buffer.trim().parse::<i32>()?;
    Ok(number)
}
```
you see? its implementing the `Error`,`Display`, `Debug` traits automatically, which helps you get rid of a ton of overhead.

it also implements the `From` trait for every type that is specified in the enum variants with the `#[from]` attribute macro.

also note that this implementation:
```rust
impl std::convert::From<std::io::Error> for ReadNumberError {
    #[allow(deprecated)]
    fn from(source: std::io::Error) -> Self {
        ReadNumberError::ReadLine { 0: source }
    }
}
```
is totally different from this one (which doesnt compile with the message `error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate`):
```rust
impl From<ParseIntError> for std::io::Error {
    fn from(error: ParseIntError) {
        // second argument is the message
        Self::new(ErrorKind::Other, error.to_string())
    }
}
```
(ignore the errors order, doesnt matter for this topic)

because in the second one we are forced to create a new error from scratch, while in the first one we are just wrapping/putting the source error in our error type.

**Comment by alexzanderr** [comment]
note that for this specific issue i've created a branch: https://github.com/alexzanderr/rust-dev-guide/tree/issue-1

which after many discussions and pushes will be merged in main from a pull request

**Comment by dragos-ionescu** [comment]
Issue solved.
